Apply upstream (rest-server) API changes
restic/caddy pull request #3
Opened 2018-07-16 07:33 UTC by claui

In June 2018, dependency [rest-server](https://github.com/restic/rest-server) cleaned up [its API a little](https://github.com/restic/rest-server/pull/67), breaking the restic Caddy plugin build in the process.

Since then, attempting to build the restic Caddy plugin produces the following errors:

```
build/src/github.com/restic/caddy/setup.go:24:4: undefined: restserver.Config
build/src/github.com/restic/caddy/setup.go:40:19: undefined: restserver.NewMux
```

This PR applies the upstream API changes to fix the errors.

**Note:** This is a best-effort fix. I don’t even use restic, and saw the build error by pure coincidence because I happened to include the plugin accidentally. This fix is therefore completely untested.
**If possible, please test before merging.**

2018-07-16 14:34 UTC, mholt requested changes
Thanks! I've been meaning to get around to this. I think this is pretty close, but I'll need to test it out like you said. Just a couple minor changes in the meantime.

2018-07-16 14:34 UTC, mholt commented on setup.go
> +	var httpConfig *httpserver.SiteConfig
Get rid of these zero-value declarations; variables are both assigned below

2018-07-16 14:34 UTC, mholt commented on setup.go
> +	restConfig = restserver.Server{}
Turn this into a `:=`

2018-07-16 14:34 UTC, mholt commented on setup.go
> +	httpConfig = httpserver.GetConfig(c)
Turn this into a `:=`

2018-07-16 15:33 UTC, claui commented
Done.

2018-07-31 06:22 UTC, claui commented
@mholt Have you had a chance to test the changes yet?

2018-08-01 04:20 UTC, mholt approved these changes

2018-08-01 04:21 UTC, mholt commented
Thanks for the reminder! Sorry I lost track of this. Appreciate your contribution, especially since you're not even a restic user. :)

2018-08-01 04:21 UTC, merged